comment:
  layout: "header, diff"
  require_changes: no  # if 'yes', only comment on PRs with coverage changes
  behavior: default
  flags: no
  paths: no
  branches: no
coverage:
  status:
    project: null  # overall project coverage
    patch:
      default:
        target: 100%  # target percentage for patch/diff coverage
